// Auth
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const CONFIRM_ACCOUNT_START = "CONFIRM_ACCOUNT_START";
export const CONFIRM_ACCOUNT_SUCCESS = "CONFIRM_ACCOUNT_SUCCESS";
export const CONFIRM_ACCOUNT_FAILED = "CONFIRM_ACCOUNT_FAILED";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const RESET_ERRORS = "RESET_ERRORS";

// Game
export const ADD_GAME_START = "ADD_GAME_START";
export const ADD_GAME_SUCCESS = "ADD_GAME_SUCCESS";
export const ADD_GAME_FAILED = "ADD_GAME_FAILED";


export const GET_GAME_START = "GET_GAME_START";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_FAILED = "GET_GAME_FAILED";

export const GET_GAMES_START = "GET_GAMES_START";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_FAILED = "GET_GAMES_FAILED";

export const EDIT_GAME_START = "EDIT_GAME_START";
export const EDIT_GAME_SUCCESS = "EDIT_GAME_SUCCESS";
export const EDIT_GAME_FAILED = "EDIT_GAME_FAILED";

export const DELETE_GAME_START = "DELETE_GAME_START";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAILED = "DELETE_GAME_FAILED";

export const ADD_GAMEREVIEW_START = "ADD_GAMEREVIEW_START";
export const ADD_GAMEREVIEW_SUCCESS = "ADD_GAMEREVIEW_SUCCESS";
export const ADD_GAMEREVIEW_FAILED = "ADD_GAMEREVIEW_FAILED";

// Guide

export const ADD_GUIDE_START = "ADD_GUIDE_START";
export const ADD_GUIDE_SUCCESS = "ADD_GUIDE_SUCCESS";
export const ADD_GUIDE_FAILED = "ADD_GUIDE_FAILED";

export const GET_GUIDE_START = "GET_GUIDE_START";
export const GET_GUIDE_SUCCESS = "GET_GUIDE_SUCCESS";
export const GET_GUIDE_FAILED = "GET_GUIDE_FAILED";

export const EDIT_GUIDE_START = "EDIT_GUIDE_START";
export const EDIT_GUIDE_SUCCESS = "EDIT_GUIDE_SUCCESS";
export const EDIT_GUIDE_FAILED = "EDIT_GUIDE_FAILED";

export const DELETE_GUIDE_START = "DELETE_GUIDE_START";
export const DELETE_GUIDE_SUCCESS = "DELETE_GUIDE_SUCCESS";
export const DELETE_GUIDE_FAILED = "DELETE_GUIDE_FAILED";

export const GET_GUIDES_START = "GET_GUIDES_START";
export const GET_GUIDES_SUCCESS = "GET_GUIDES_SUCCESS";
export const GET_GUIDES_FAILED = "GET_GUIDES_FAILED";

export const ADD_GUIDEREVIEW_START = "ADD_GUIDEREVIEW_START";
export const ADD_GUIDEREVIEW_SUCCESS = "ADD_GUIDEREVIEW_SUCCESS";
export const ADD_GUIDEREVIEW_FAILED = "ADD_GUIDEREVIEW_FAILED";

// User
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";